/*
 * The MySQL schema: every table as of PostgreSQL migration 0020 (the last one before the move to MySQL), translated
 * from the PostgreSQL catalog. Applied once, to a database that has no tables yet; later changes go in migrations.ts.
 *
 * How PostgreSQL types were carried over:
 *   uuid          varchar(36). Ids are made by the application (crypto.randomUUID); DEFAULT (uuid()) covers manual inserts.
 *   timestamptz   datetime(3) holding UTC. Every connection sets its time zone to +00:00 (see index.ts).
 *   text          varchar(n) when the column is indexed or has a default, otherwise mediumtext.
 *   jsonb, arrays json. A PostgreSQL array column is a JSON array here.
 *   serial        int AUTO_INCREMENT.
 * Text is utf8mb4 with the utf8mb4_bin collation, so comparisons and unique keys are case-sensitive, as they were.
 * A partial index became a plain one (a unique key allows any number of NULLs), and the unique index on
 * lower(name) became a stored generated column with a unique key.
 */
export const baselineName = "0001_mysql_baseline";

export const baselineStatements: string[] = [
  `CREATE TABLE socialflow_account_metrics (
  id varchar(36) NOT NULL DEFAULT (uuid()),
  connected_account_id varchar(36) NOT NULL,
  captured_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  followers int,
  media_count int,
  views_total bigint,
  PRIMARY KEY (id),
  KEY socialflow_account_metrics_idx (connected_account_id, captured_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin`,
  `CREATE TABLE socialflow_account_queues (
  connected_account_id varchar(36) NOT NULL,
  timezone varchar(64) NOT NULL,
  paused boolean NOT NULL DEFAULT 0,
  updated_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (connected_account_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin`,
  `CREATE TABLE socialflow_ai_usage (
  id varchar(36) NOT NULL DEFAULT (uuid()),
  workspace_id varchar(36) NOT NULL,
  user_id varchar(36),
  task varchar(255) NOT NULL,
  input_tokens int NOT NULL DEFAULT 0,
  output_tokens int NOT NULL DEFAULT 0,
  model mediumtext NOT NULL,
  created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY socialflow_ai_usage_workspace_idx (workspace_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin`,
  `CREATE TABLE socialflow_approval_settings (
  workspace_id varchar(36) NOT NULL,
  required boolean NOT NULL DEFAULT 0,
  updated_by varchar(36),
  updated_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (workspace_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin`,
  `CREATE TABLE socialflow_audit_log (
  id varchar(36) NOT NULL DEFAULT (uuid()),
  workspace_id varchar(36) NOT NULL,
  actor_user_id varchar(36),
  action mediumtext NOT NULL,
  target mediumtext,
  detail json NOT NULL DEFAULT (JSON_OBJECT()),
  created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY socialflow_audit_workspace_idx (workspace_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin`,
  `CREATE TABLE socialflow_automation_items (
  id varchar(36) NOT NULL DEFAULT (uuid()),
  automation_id varchar(36) NOT NULL,
  item_key varchar(500) NOT NULL,
  title mediumtext,
  url mediumtext,
  published_at datetime(3),
  status varchar(64) NOT NULL,
  post_id varchar(36),
  attempts int NOT NULL DEFAULT 0,
  error mediumtext,
  created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY socialflow_automation_items_automation_id_item_key_key (automation_id, item_key),
  KEY socialflow_automation_items_recent_idx (automation_id, created_at),
  CONSTRAINT socialflow_automation_items_status_check CHECK (status IN ('pending', 'posted', 'skipped', 'failed', 'seen'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin`,
  `CREATE TABLE socialflow_automation_runs (
  id varchar(36) NOT NULL DEFAULT (uuid()),
  automation_id varchar(36) NOT NULL,
  started_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  finished_at datetime(3),
  status varchar(64) NOT NULL,
  items_found int NOT NULL DEFAULT 0,
  items_new int NOT NULL DEFAULT 0,
  posts_created int NOT NULL DEFAULT 0,
  error mediumtext,
  PRIMARY KEY (id),
  KEY socialflow_automation_runs_idx (automation_id, started_at),
  CONSTRAINT socialflow_automation_runs_status_check CHECK (status IN ('success', 'no_new', 'partial', 'failed'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin`,
  `CREATE TABLE socialflow_automations (
  id varchar(36) NOT NULL DEFAULT (uuid()),
  workspace_id varchar(36) NOT NULL,
  kind varchar(64) NOT NULL,
  name mediumtext NOT NULL,
  source_url mediumtext NOT NULL,
  status varchar(64) NOT NULL DEFAULT 'active',
  config json NOT NULL DEFAULT (JSON_OBJECT()),
  last_run_at datetime(3),
  next_run_at datetime(3),
  last_status varchar(64),
  last_error mediumtext,
  consecutive_failures int NOT NULL DEFAULT 0,
  baseline_at datetime(3),
  created_by_user_id varchar(36),
  created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY socialflow_automations_due_idx (status, next_run_at),
  KEY socialflow_automations_workspace_idx (workspace_id),
  CONSTRAINT socialflow_automations_kind_check CHECK (kind IN ('wordpress', 'rss', 'wordpress_plugin')),
  CONSTRAINT socialflow_automations_status_check CHECK (status IN ('active', 'paused', 'error'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin`,
  `CREATE TABLE socialflow_brand_voices (
  id varchar(36) NOT NULL DEFAULT (uuid()),
  workspace_id varchar(36) NOT NULL,
  name mediumtext NOT NULL,
  description mediumtext NOT NULL DEFAULT (''),
  tone_notes mediumtext NOT NULL DEFAULT (''),
  do_words json NOT NULL DEFAULT (JSON_ARRAY()),
  dont_words json NOT NULL DEFAULT (JSON_ARRAY()),
  updated_by varchar(36),
  created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY socialflow_brand_voices_workspace_idx (workspace_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin`,
  `CREATE TABLE socialflow_bulk_imports (
  id varchar(36) NOT NULL DEFAULT (uuid()),
  workspace_id varchar(36) NOT NULL,
  created_by_user_id varchar(36),
  file_name mediumtext NOT NULL,
  total_rows int NOT NULL DEFAULT 0,
  created_count int NOT NULL DEFAULT 0,
  failed_count int NOT NULL DEFAULT 0,
  status varchar(64) NOT NULL,
  mode varchar(64) NOT NULL,
  errors json NOT NULL DEFAULT (JSON_ARRAY()),
  created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY socialflow_bulk_imports_workspace_idx (workspace_id, created_at),
  CONSTRAINT socialflow_bulk_imports_status_check CHECK (status IN ('completed', 'partial', 'failed'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin`,
  `CREATE TABLE socialflow_connected_accounts (
  id varchar(36) NOT NULL DEFAULT (uuid()),
  workspace_id varchar(36) NOT NULL,
  platform varchar(64) NOT NULL,
  account_type varchar(64) NOT NULL,
  external_account_id varchar(255) NOT NULL,
  display_name mediumtext NOT NULL,
  username mediumtext,
  avatar_url mediumtext,
  access_token_encrypted mediumtext NOT NULL,
  refresh_token_encrypted mediumtext,
  token_expires_at datetime(3),
  refresh_token_expires_at datetime(3),
  scopes json NOT NULL DEFAULT (JSON_ARRAY()),
  status varchar(64) NOT NULL DEFAULT 'active',
  status_detail mediumtext,
  authorized_by_external_user_id mediumtext,
  metadata json NOT NULL DEFAULT (JSON_OBJECT()),
  last_verified_at datetime(3),
  created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY socialflow_connected_accounts_unique_idx (workspace_id, platform, external_account_id),
  KEY socialflow_connected_accounts_workspace_idx (workspace_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin`,
  `CREATE TABLE socialflow_custom_fields (
  id varchar(36) NOT NULL DEFAULT (uuid()),
  workspace_id varchar(36) NOT NULL,
  \`key\` varchar(191) NOT NULL,
  label mediumtext NOT NULL,
  type varchar(64) NOT NULL,
  options json NOT NULL DEFAULT (JSON_ARRAY()),
  required boolean NOT NULL DEFAULT 0,
  position int NOT NULL DEFAULT 0,
  created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY socialflow_custom_fields_workspace_id_key_key (workspace_id, \`key\`),
  CONSTRAINT socialflow_custom_fields_type_check CHECK (type IN ('text', 'number', 'date', 'select', 'url'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin`,
  `CREATE TABLE socialflow_data_deletions (
  id varchar(36) NOT NULL DEFAULT (uuid()),
  confirmation_code varchar(128) NOT NULL,
  platform varchar(64) NOT NULL,
  external_user_id varchar(255) NOT NULL,
  accounts_removed int NOT NULL DEFAULT 0,
  status varchar(64) NOT NULL DEFAULT 'completed',
  requested_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  completed_at datetime(3),
  PRIMARY KEY (id),
  UNIQUE KEY socialflow_data_deletions_confirmation_code_key (confirmation_code),
  KEY socialflow_data_deletions_user_idx (platform, external_user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin`,
  `CREATE TABLE socialflow_inbox_items (
  id varchar(36) NOT NULL DEFAULT (uuid()),
  workspace_id varchar(36) NOT NULL,
  connected_account_id varchar(36) NOT NULL,
  post_target_id varchar(36),
  platform varchar(64) NOT NULL,
  external_id varchar(255) NOT NULL,
  external_post_id mediumtext,
  parent_external_id mediumtext,
  author_name mediumtext NOT NULL,
  author_avatar mediumtext,
  body mediumtext NOT NULL,
  created_at_network datetime(3) NOT NULL,
  status varchar(64) NOT NULL DEFAULT 'open',
  read_at datetime(3),
  assigned_to_user_id varchar(36),
  replied boolean NOT NULL DEFAULT 0,
  created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  kind varchar(64) NOT NULL DEFAULT 'comment',
  thread_id varchar(255),
  participant_id mediumtext,
  from_page boolean NOT NULL DEFAULT 0,
  permalink mediumtext,
  PRIMARY KEY (id),
  UNIQUE KEY socialflow_inbox_items_external_idx (connected_account_id, external_id),
  KEY socialflow_inbox_items_kind_idx (workspace_id, kind, status, created_at_network),
  KEY socialflow_inbox_items_list_idx (workspace_id, status, created_at_network),
  KEY socialflow_inbox_items_thread_idx (connected_account_id, thread_id, created_at_network),
  CONSTRAINT socialflow_inbox_items_kind_check CHECK (kind IN ('comment', 'message', 'mention'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin`,
  `CREATE TABLE socialflow_inbox_replies (
  id varchar(36) NOT NULL DEFAULT (uuid()),
  item_id varchar(36) NOT NULL,
  user_id varchar(36),
  body mediumtext NOT NULL,
  status varchar(64) NOT NULL,
  error mediumtext,
  external_id mediumtext,
  created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY socialflow_inbox_replies_item_idx (item_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin`,
  `CREATE TABLE socialflow_inbox_sync (
  connected_account_id varchar(36) NOT NULL,
  last_synced_at datetime(3),
  last_error mediumtext,
  posts_read int NOT NULL DEFAULT 0,
  messages_error mediumtext,
  mentions_error mediumtext,
  messages_synced_at datetime(3),
  mentions_synced_at datetime(3),
  PRIMARY KEY (connected_account_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin`,
  `CREATE TABLE socialflow_invitations (
  id varchar(36) NOT NULL DEFAULT (uuid()),
  workspace_id varchar(36) NOT NULL,
  email mediumtext NOT NULL,
  role varchar(64) NOT NULL,
  invited_by_user_id varchar(36),
  token_hash varchar(128) NOT NULL,
  expires_at datetime(3) NOT NULL,
  accepted_at datetime(3),
  revoked_at datetime(3),
  created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY socialflow_invitations_token_idx (token_hash),
  KEY socialflow_invitations_workspace_idx (workspace_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin`,
  `CREATE TABLE socialflow_library_folders (
  id varchar(36) NOT NULL DEFAULT (uuid()),
  workspace_id varchar(36) NOT NULL,
  name varchar(255) NOT NULL,
  created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  name_key varchar(255) GENERATED ALWAYS AS (lower(name)) STORED,
  PRIMARY KEY (id),
  UNIQUE KEY socialflow_library_folders_name_unique (workspace_id, name_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin`,
  `CREATE TABLE socialflow_library_items (
  id varchar(36) NOT NULL DEFAULT (uuid()),
  workspace_id varchar(36) NOT NULL,
  kind varchar(64) NOT NULL,
  title mediumtext NOT NULL,
  body mediumtext,
  media_id varchar(36),
  folder_id varchar(36),
  labels json NOT NULL DEFAULT (JSON_ARRAY()),
  favorite boolean NOT NULL DEFAULT 0,
  use_count int NOT NULL DEFAULT 0,
  last_used_at datetime(3),
  created_by varchar(36),
  created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY socialflow_library_items_media_idx (media_id),
  KEY socialflow_library_items_ws_idx (workspace_id, created_at),
  CONSTRAINT socialflow_library_items_kind_check CHECK (kind IN ('media', 'caption', 'template', 'snippet'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin`,
  `CREATE TABLE socialflow_media (
  id varchar(36) NOT NULL DEFAULT (uuid()),
  workspace_id varchar(36) NOT NULL,
  uploaded_by_user_id varchar(36),
  kind varchar(64) NOT NULL,
  mime_type mediumtext NOT NULL,
  original_name mediumtext NOT NULL,
  size_bytes int NOT NULL,
  storage_key mediumtext NOT NULL,
  width int,
  height int,
  duration_ms int,
  created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY socialflow_media_workspace_idx (workspace_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin`,
  `CREATE TABLE socialflow_mention_groups (
  id varchar(36) NOT NULL DEFAULT (uuid()),
  workspace_id varchar(36) NOT NULL,
  name varchar(255) NOT NULL,
  handles json NOT NULL DEFAULT (JSON_ARRAY()),
  created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY socialflow_mention_groups_workspace_id_name_key (workspace_id, name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin`,
  `CREATE TABLE socialflow_oauth_states (
  id int NOT NULL AUTO_INCREMENT,
  state_hash varchar(128) NOT NULL,
  session_id int NOT NULL,
  workspace_id varchar(36) NOT NULL,
  platform varchar(64) NOT NULL,
  reconnect_account_id varchar(36),
  code_verifier_encrypted mediumtext,
  expires_at datetime(3) NOT NULL,
  created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY socialflow_oauth_states_expires_idx (expires_at),
  UNIQUE KEY socialflow_oauth_states_hash_idx (state_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin`,
  `CREATE TABLE socialflow_password_resets (
  id varchar(36) NOT NULL DEFAULT (uuid()),
  user_id varchar(36) NOT NULL,
  token_hash varchar(128) NOT NULL,
  expires_at datetime(3) NOT NULL,
  used_at datetime(3),
  created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY socialflow_password_resets_token_hash_key (token_hash),
  KEY socialflow_password_resets_user_idx (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin`,
  `CREATE TABLE socialflow_pending_connections (
  id varchar(36) NOT NULL DEFAULT (uuid()),
  workspace_id varchar(36) NOT NULL,
  platform varchar(64) NOT NULL,
  payload_encrypted mediumtext NOT NULL,
  candidates json NOT NULL,
  expires_at datetime(3) NOT NULL,
  created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY socialflow_pending_connections_workspace_idx (workspace_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin`,
  `CREATE TABLE socialflow_post_approval_comments (
  id varchar(36) NOT NULL DEFAULT (uuid()),
  approval_id varchar(36) NOT NULL,
  user_id varchar(36),
  body mediumtext NOT NULL,
  created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY socialflow_post_approval_comments_idx (approval_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin`,
  `CREATE TABLE socialflow_post_approvals (
  id varchar(36) NOT NULL DEFAULT (uuid()),
  post_id varchar(36) NOT NULL,
  workspace_id varchar(36) NOT NULL,
  status varchar(64) NOT NULL DEFAULT 'pending',
  requested_by varchar(36),
  requested_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  decided_by varchar(36),
  decided_at datetime(3),
  note mediumtext,
  PRIMARY KEY (id),
  UNIQUE KEY socialflow_post_approvals_post_idx (post_id),
  KEY socialflow_post_approvals_ws_status_idx (workspace_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin`,
  `CREATE TABLE socialflow_post_custom_values (
  post_id varchar(36) NOT NULL,
  field_id varchar(36) NOT NULL,
  value mediumtext NOT NULL,
  PRIMARY KEY (post_id, field_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin`,
  `CREATE TABLE socialflow_post_media (
  post_id varchar(36) NOT NULL,
  media_id varchar(36) NOT NULL,
  position int NOT NULL,
  PRIMARY KEY (post_id, media_id),
  KEY socialflow_post_media_media_idx (media_id),
  UNIQUE KEY socialflow_post_media_post_id_media_id_pk (post_id, media_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin`,
  `CREATE TABLE socialflow_post_metrics (
  id varchar(36) NOT NULL DEFAULT (uuid()),
  post_target_id varchar(36) NOT NULL,
  captured_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  likes int,
  comments int,
  shares int,
  views bigint,
  impressions bigint,
  reach bigint,
  saves int,
  PRIMARY KEY (id),
  KEY socialflow_post_metrics_idx (post_target_id, captured_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin`,
  `CREATE TABLE socialflow_post_platform_content (
  post_id varchar(36) NOT NULL,
  platform varchar(64) NOT NULL,
  content mediumtext NOT NULL,
  PRIMARY KEY (post_id, platform)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin`,
  `CREATE TABLE socialflow_post_tags (
  post_id varchar(36) NOT NULL,
  tag_id varchar(36) NOT NULL,
  PRIMARY KEY (post_id, tag_id),
  KEY socialflow_post_tags_tag_idx (tag_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin`,
  `CREATE TABLE socialflow_post_targets (
  id varchar(36) NOT NULL DEFAULT (uuid()),
  post_id varchar(36) NOT NULL,
  connected_account_id varchar(36) NOT NULL,
  status varchar(64) NOT NULL DEFAULT 'draft',
  error_message mediumtext,
  external_post_id mediumtext,
  first_comment_status varchar(64),
  first_comment_error mediumtext,
  first_comment_external_id mediumtext,
  PRIMARY KEY (id),
  KEY socialflow_post_targets_account_idx (connected_account_id),
  UNIQUE KEY socialflow_post_targets_unique_idx (post_id, connected_account_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin`,
  `CREATE TABLE socialflow_posts (
  id varchar(36) NOT NULL DEFAULT (uuid()),
  workspace_id varchar(36) NOT NULL,
  created_by_user_id varchar(36),
  content mediumtext NOT NULL DEFAULT (''),
  status varchar(64) NOT NULL DEFAULT 'draft',
  scheduled_at datetime(3),
  published_at datetime(3),
  created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  recurrence_id varchar(36),
  occurrence_index int,
  first_comment mediumtext,
  link_url mediumtext,
  link_title mediumtext,
  link_description mediumtext,
  link_image_url mediumtext,
  PRIMARY KEY (id),
  UNIQUE KEY socialflow_posts_occurrence_idx (recurrence_id, occurrence_index),
  KEY socialflow_posts_workspace_schedule_idx (workspace_id, scheduled_at),
  KEY socialflow_posts_workspace_status_idx (workspace_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin`,
  `CREATE TABLE socialflow_queue_slots (
  id varchar(36) NOT NULL DEFAULT (uuid()),
  connected_account_id varchar(36) NOT NULL,
  weekday smallint NOT NULL,
  minute_of_day smallint NOT NULL,
  PRIMARY KEY (id),
  KEY socialflow_queue_slots_account_idx (connected_account_id),
  UNIQUE KEY socialflow_queue_slots_connected_account_id_weekday_minute__key (connected_account_id, weekday, minute_of_day),
  CONSTRAINT socialflow_queue_slots_minute_of_day_check CHECK (((minute_of_day >= 0) AND (minute_of_day <= 1439))),
  CONSTRAINT socialflow_queue_slots_weekday_check CHECK (((weekday >= 0) AND (weekday <= 6)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin`,
  `CREATE TABLE socialflow_recurrences (
  id varchar(36) NOT NULL DEFAULT (uuid()),
  workspace_id varchar(36) NOT NULL,
  created_by_user_id varchar(36),
  frequency varchar(64) NOT NULL,
  \`interval\` smallint NOT NULL DEFAULT 1,
  weekdays json NOT NULL DEFAULT (JSON_ARRAY()),
  day_of_month smallint,
  minute_of_day smallint NOT NULL,
  timezone varchar(64) NOT NULL,
  start_date date NOT NULL,
  end_date date,
  max_occurrences int,
  occurrences_created int NOT NULL DEFAULT 0,
  next_run_at datetime(3),
  paused boolean NOT NULL DEFAULT 0,
  content mediumtext NOT NULL DEFAULT (''),
  first_comment mediumtext,
  platform_content json NOT NULL DEFAULT (JSON_OBJECT()),
  connected_account_ids json NOT NULL DEFAULT (JSON_ARRAY()),
  media_ids json NOT NULL DEFAULT (JSON_ARRAY()),
  tag_ids json NOT NULL DEFAULT (JSON_ARRAY()),
  created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY socialflow_recurrences_due_idx (next_run_at),
  KEY socialflow_recurrences_workspace_idx (workspace_id),
  CONSTRAINT socialflow_recurrences_day_of_month_check CHECK (((day_of_month >= 1) AND (day_of_month <= 31))),
  CONSTRAINT socialflow_recurrences_frequency_check CHECK (frequency IN ('daily', 'weekly', 'monthly')),
  CONSTRAINT socialflow_recurrences_interval_check CHECK (((\`interval\` >= 1) AND (\`interval\` <= 52))),
  CONSTRAINT socialflow_recurrences_max_occurrences_check CHECK ((max_occurrences > 0)),
  CONSTRAINT socialflow_recurrences_minute_of_day_check CHECK (((minute_of_day >= 0) AND (minute_of_day <= 1439)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin`,
  `CREATE TABLE socialflow_report_runs (
  id varchar(36) NOT NULL DEFAULT (uuid()),
  schedule_id varchar(36) NOT NULL,
  ran_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  status varchar(64) NOT NULL,
  error mediumtext,
  recipient_count int NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  KEY socialflow_report_runs_schedule_idx (schedule_id, ran_at),
  CONSTRAINT socialflow_report_runs_status_check CHECK (status IN ('sent', 'failed'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin`,
  `CREATE TABLE socialflow_report_schedules (
  id varchar(36) NOT NULL DEFAULT (uuid()),
  workspace_id varchar(36) NOT NULL,
  created_by varchar(36),
  name mediumtext NOT NULL,
  frequency varchar(64) NOT NULL,
  weekday int,
  day_of_month int,
  hour int NOT NULL,
  timezone varchar(64) NOT NULL DEFAULT 'UTC',
  range_key varchar(64) NOT NULL DEFAULT '7d',
  platform varchar(64),
  account_id varchar(36),
  recipients json NOT NULL DEFAULT (JSON_ARRAY()),
  enabled boolean NOT NULL DEFAULT 1,
  last_run_at datetime(3),
  last_status varchar(64),
  last_error mediumtext,
  next_run_at datetime(3),
  created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY socialflow_report_schedules_due_idx (next_run_at),
  KEY socialflow_report_schedules_workspace_idx (workspace_id),
  CONSTRAINT socialflow_report_schedules_day_of_month_check CHECK (((day_of_month >= 1) AND (day_of_month <= 28))),
  CONSTRAINT socialflow_report_schedules_frequency_check CHECK (frequency IN ('weekly', 'monthly')),
  CONSTRAINT socialflow_report_schedules_hour_check CHECK (((hour >= 0) AND (hour <= 23))),
  CONSTRAINT socialflow_report_schedules_range_key_check CHECK (range_key IN ('7d', '30d', '90d')),
  CONSTRAINT socialflow_report_schedules_weekday_check CHECK (((weekday >= 0) AND (weekday <= 6)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin`,
  `CREATE TABLE socialflow_sessions (
  id int NOT NULL AUTO_INCREMENT,
  token_hash varchar(128) NOT NULL,
  user_id varchar(36) NOT NULL,
  expires_at datetime(3) NOT NULL,
  created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  active_workspace_id varchar(36),
  PRIMARY KEY (id),
  UNIQUE KEY socialflow_sessions_token_hash_idx (token_hash),
  KEY socialflow_sessions_user_idx (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin`,
  `CREATE TABLE socialflow_tags (
  id varchar(36) NOT NULL DEFAULT (uuid()),
  workspace_id varchar(36) NOT NULL,
  name varchar(255) NOT NULL,
  color varchar(32) NOT NULL DEFAULT '#6366f1',
  created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY socialflow_tags_workspace_id_name_key (workspace_id, name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin`,
  `CREATE TABLE socialflow_users (
  id varchar(36) NOT NULL DEFAULT (uuid()),
  email varchar(320) NOT NULL,
  password_hash mediumtext NOT NULL,
  display_name mediumtext,
  created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY socialflow_users_email_idx (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin`,
  `CREATE TABLE socialflow_wordpress_connections (
  id varchar(36) NOT NULL DEFAULT (uuid()),
  automation_id varchar(36) NOT NULL,
  workspace_id varchar(36) NOT NULL,
  key_id varchar(64) NOT NULL,
  secret_encrypted mediumtext NOT NULL,
  status varchar(64) NOT NULL DEFAULT 'pending',
  site_url mediumtext,
  site_name mediumtext,
  wp_version mediumtext,
  plugin_version mediumtext,
  connected_at datetime(3),
  last_seen_at datetime(3),
  last_post_at datetime(3),
  created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY socialflow_wordpress_connections_automation_id_key (automation_id),
  UNIQUE KEY socialflow_wordpress_connections_key_id_key (key_id),
  KEY socialflow_wordpress_connections_workspace_idx (workspace_id),
  CONSTRAINT socialflow_wordpress_connections_status_check CHECK (status IN ('pending', 'connected', 'disconnected'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin`,
  `CREATE TABLE socialflow_workspace_members (
  id varchar(36) NOT NULL DEFAULT (uuid()),
  workspace_id varchar(36) NOT NULL,
  user_id varchar(36) NOT NULL,
  role varchar(64) NOT NULL DEFAULT 'owner',
  created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY socialflow_workspace_members_unique_idx (workspace_id, user_id),
  KEY socialflow_workspace_members_user_idx (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin`,
  `CREATE TABLE socialflow_workspaces (
  id varchar(36) NOT NULL DEFAULT (uuid()),
  name varchar(255) NOT NULL DEFAULT 'My workspace',
  owner_user_id varchar(36),
  created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin`,
  `ALTER TABLE socialflow_account_metrics ADD CONSTRAINT socialflow_account_metrics_connected_account_id_fkey FOREIGN KEY (connected_account_id) REFERENCES socialflow_connected_accounts (id) ON DELETE CASCADE`,
  `ALTER TABLE socialflow_account_queues ADD CONSTRAINT socialflow_account_queues_connected_account_id_fkey FOREIGN KEY (connected_account_id) REFERENCES socialflow_connected_accounts (id) ON DELETE CASCADE`,
  `ALTER TABLE socialflow_ai_usage ADD CONSTRAINT socialflow_ai_usage_user_id_fkey FOREIGN KEY (user_id) REFERENCES socialflow_users (id) ON DELETE SET NULL`,
  `ALTER TABLE socialflow_ai_usage ADD CONSTRAINT socialflow_ai_usage_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES socialflow_workspaces (id) ON DELETE CASCADE`,
  `ALTER TABLE socialflow_approval_settings ADD CONSTRAINT socialflow_approval_settings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES socialflow_users (id) ON DELETE SET NULL`,
  `ALTER TABLE socialflow_approval_settings ADD CONSTRAINT socialflow_approval_settings_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES socialflow_workspaces (id) ON DELETE CASCADE`,
  `ALTER TABLE socialflow_audit_log ADD CONSTRAINT socialflow_audit_log_actor_user_id_fkey FOREIGN KEY (actor_user_id) REFERENCES socialflow_users (id) ON DELETE SET NULL`,
  `ALTER TABLE socialflow_audit_log ADD CONSTRAINT socialflow_audit_log_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES socialflow_workspaces (id) ON DELETE CASCADE`,
  `ALTER TABLE socialflow_automation_items ADD CONSTRAINT socialflow_automation_items_automation_id_fkey FOREIGN KEY (automation_id) REFERENCES socialflow_automations (id) ON DELETE CASCADE`,
  `ALTER TABLE socialflow_automation_items ADD CONSTRAINT socialflow_automation_items_post_id_fkey FOREIGN KEY (post_id) REFERENCES socialflow_posts (id) ON DELETE SET NULL`,
  `ALTER TABLE socialflow_automation_runs ADD CONSTRAINT socialflow_automation_runs_automation_id_fkey FOREIGN KEY (automation_id) REFERENCES socialflow_automations (id) ON DELETE CASCADE`,
  `ALTER TABLE socialflow_automations ADD CONSTRAINT socialflow_automations_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES socialflow_users (id) ON DELETE SET NULL`,
  `ALTER TABLE socialflow_automations ADD CONSTRAINT socialflow_automations_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES socialflow_workspaces (id) ON DELETE CASCADE`,
  `ALTER TABLE socialflow_brand_voices ADD CONSTRAINT socialflow_brand_voices_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES socialflow_users (id) ON DELETE SET NULL`,
  `ALTER TABLE socialflow_brand_voices ADD CONSTRAINT socialflow_brand_voices_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES socialflow_workspaces (id) ON DELETE CASCADE`,
  `ALTER TABLE socialflow_bulk_imports ADD CONSTRAINT socialflow_bulk_imports_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES socialflow_users (id) ON DELETE SET NULL`,
  `ALTER TABLE socialflow_bulk_imports ADD CONSTRAINT socialflow_bulk_imports_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES socialflow_workspaces (id) ON DELETE CASCADE`,
  `ALTER TABLE socialflow_connected_accounts ADD CONSTRAINT socialflow_connected_accounts_workspace_id_socialflow_workspace FOREIGN KEY (workspace_id) REFERENCES socialflow_workspaces (id) ON DELETE CASCADE`,
  `ALTER TABLE socialflow_custom_fields ADD CONSTRAINT socialflow_custom_fields_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES socialflow_workspaces (id) ON DELETE CASCADE`,
  `ALTER TABLE socialflow_inbox_items ADD CONSTRAINT socialflow_inbox_items_assigned_to_user_id_fkey FOREIGN KEY (assigned_to_user_id) REFERENCES socialflow_users (id) ON DELETE SET NULL`,
  `ALTER TABLE socialflow_inbox_items ADD CONSTRAINT socialflow_inbox_items_connected_account_id_fkey FOREIGN KEY (connected_account_id) REFERENCES socialflow_connected_accounts (id) ON DELETE CASCADE`,
  `ALTER TABLE socialflow_inbox_items ADD CONSTRAINT socialflow_inbox_items_post_target_id_fkey FOREIGN KEY (post_target_id) REFERENCES socialflow_post_targets (id) ON DELETE SET NULL`,
  `ALTER TABLE socialflow_inbox_items ADD CONSTRAINT socialflow_inbox_items_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES socialflow_workspaces (id) ON DELETE CASCADE`,
  `ALTER TABLE socialflow_inbox_replies ADD CONSTRAINT socialflow_inbox_replies_item_id_fkey FOREIGN KEY (item_id) REFERENCES socialflow_inbox_items (id) ON DELETE CASCADE`,
  `ALTER TABLE socialflow_inbox_replies ADD CONSTRAINT socialflow_inbox_replies_user_id_fkey FOREIGN KEY (user_id) REFERENCES socialflow_users (id) ON DELETE SET NULL`,
  `ALTER TABLE socialflow_inbox_sync ADD CONSTRAINT socialflow_inbox_sync_connected_account_id_fkey FOREIGN KEY (connected_account_id) REFERENCES socialflow_connected_accounts (id) ON DELETE CASCADE`,
  `ALTER TABLE socialflow_invitations ADD CONSTRAINT socialflow_invitations_invited_by_user_id_fkey FOREIGN KEY (invited_by_user_id) REFERENCES socialflow_users (id) ON DELETE SET NULL`,
  `ALTER TABLE socialflow_invitations ADD CONSTRAINT socialflow_invitations_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES socialflow_workspaces (id) ON DELETE CASCADE`,
  `ALTER TABLE socialflow_library_folders ADD CONSTRAINT socialflow_library_folders_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES socialflow_workspaces (id) ON DELETE CASCADE`,
  `ALTER TABLE socialflow_library_items ADD CONSTRAINT socialflow_library_items_created_by_fkey FOREIGN KEY (created_by) REFERENCES socialflow_users (id) ON DELETE SET NULL`,
  `ALTER TABLE socialflow_library_items ADD CONSTRAINT socialflow_library_items_folder_id_fkey FOREIGN KEY (folder_id) REFERENCES socialflow_library_folders (id) ON DELETE SET NULL`,
  `ALTER TABLE socialflow_library_items ADD CONSTRAINT socialflow_library_items_media_id_fkey FOREIGN KEY (media_id) REFERENCES socialflow_media (id) ON DELETE CASCADE`,
  `ALTER TABLE socialflow_library_items ADD CONSTRAINT socialflow_library_items_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES socialflow_workspaces (id) ON DELETE CASCADE`,
  `ALTER TABLE socialflow_media ADD CONSTRAINT socialflow_media_uploaded_by_user_id_socialflow_users_id_fk FOREIGN KEY (uploaded_by_user_id) REFERENCES socialflow_users (id) ON DELETE SET NULL`,
  `ALTER TABLE socialflow_media ADD CONSTRAINT socialflow_media_workspace_id_socialflow_workspaces_id_fk FOREIGN KEY (workspace_id) REFERENCES socialflow_workspaces (id) ON DELETE CASCADE`,
  `ALTER TABLE socialflow_mention_groups ADD CONSTRAINT socialflow_mention_groups_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES socialflow_workspaces (id) ON DELETE CASCADE`,
  `ALTER TABLE socialflow_oauth_states ADD CONSTRAINT socialflow_oauth_states_session_id_socialflow_sessions_id_fk FOREIGN KEY (session_id) REFERENCES socialflow_sessions (id) ON DELETE CASCADE`,
  `ALTER TABLE socialflow_oauth_states ADD CONSTRAINT socialflow_oauth_states_workspace_id_socialflow_workspaces_id_f FOREIGN KEY (workspace_id) REFERENCES socialflow_workspaces (id) ON DELETE CASCADE`,
  `ALTER TABLE socialflow_password_resets ADD CONSTRAINT socialflow_password_resets_user_id_fkey FOREIGN KEY (user_id) REFERENCES socialflow_users (id) ON DELETE CASCADE`,
  `ALTER TABLE socialflow_pending_connections ADD CONSTRAINT socialflow_pending_connections_workspace_id_socialflow_workspac FOREIGN KEY (workspace_id) REFERENCES socialflow_workspaces (id) ON DELETE CASCADE`,
  `ALTER TABLE socialflow_post_approval_comments ADD CONSTRAINT socialflow_post_approval_comments_approval_id_fkey FOREIGN KEY (approval_id) REFERENCES socialflow_post_approvals (id) ON DELETE CASCADE`,
  `ALTER TABLE socialflow_post_approval_comments ADD CONSTRAINT socialflow_post_approval_comments_user_id_fkey FOREIGN KEY (user_id) REFERENCES socialflow_users (id) ON DELETE SET NULL`,
  `ALTER TABLE socialflow_post_approvals ADD CONSTRAINT socialflow_post_approvals_decided_by_fkey FOREIGN KEY (decided_by) REFERENCES socialflow_users (id) ON DELETE SET NULL`,
  `ALTER TABLE socialflow_post_approvals ADD CONSTRAINT socialflow_post_approvals_post_id_fkey FOREIGN KEY (post_id) REFERENCES socialflow_posts (id) ON DELETE CASCADE`,
  `ALTER TABLE socialflow_post_approvals ADD CONSTRAINT socialflow_post_approvals_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES socialflow_users (id) ON DELETE SET NULL`,
  `ALTER TABLE socialflow_post_approvals ADD CONSTRAINT socialflow_post_approvals_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES socialflow_workspaces (id) ON DELETE CASCADE`,
  `ALTER TABLE socialflow_post_custom_values ADD CONSTRAINT socialflow_post_custom_values_field_id_fkey FOREIGN KEY (field_id) REFERENCES socialflow_custom_fields (id) ON DELETE CASCADE`,
  `ALTER TABLE socialflow_post_custom_values ADD CONSTRAINT socialflow_post_custom_values_post_id_fkey FOREIGN KEY (post_id) REFERENCES socialflow_posts (id) ON DELETE CASCADE`,
  `ALTER TABLE socialflow_post_media ADD CONSTRAINT socialflow_post_media_media_id_socialflow_media_id_fk FOREIGN KEY (media_id) REFERENCES socialflow_media (id) ON DELETE CASCADE`,
  `ALTER TABLE socialflow_post_media ADD CONSTRAINT socialflow_post_media_post_id_socialflow_posts_id_fk FOREIGN KEY (post_id) REFERENCES socialflow_posts (id) ON DELETE CASCADE`,
  `ALTER TABLE socialflow_post_metrics ADD CONSTRAINT socialflow_post_metrics_post_target_id_fkey FOREIGN KEY (post_target_id) REFERENCES socialflow_post_targets (id) ON DELETE CASCADE`,
  `ALTER TABLE socialflow_post_platform_content ADD CONSTRAINT socialflow_post_platform_content_post_id_fkey FOREIGN KEY (post_id) REFERENCES socialflow_posts (id) ON DELETE CASCADE`,
  `ALTER TABLE socialflow_post_tags ADD CONSTRAINT socialflow_post_tags_post_id_fkey FOREIGN KEY (post_id) REFERENCES socialflow_posts (id) ON DELETE CASCADE`,
  `ALTER TABLE socialflow_post_tags ADD CONSTRAINT socialflow_post_tags_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES socialflow_tags (id) ON DELETE CASCADE`,
  `ALTER TABLE socialflow_post_targets ADD CONSTRAINT socialflow_post_targets_connected_account_id_socialflow_connect FOREIGN KEY (connected_account_id) REFERENCES socialflow_connected_accounts (id) ON DELETE CASCADE`,
  `ALTER TABLE socialflow_post_targets ADD CONSTRAINT socialflow_post_targets_post_id_socialflow_posts_id_fk FOREIGN KEY (post_id) REFERENCES socialflow_posts (id) ON DELETE CASCADE`,
  `ALTER TABLE socialflow_posts ADD CONSTRAINT socialflow_posts_created_by_user_id_socialflow_users_id_fk FOREIGN KEY (created_by_user_id) REFERENCES socialflow_users (id) ON DELETE SET NULL`,
  `ALTER TABLE socialflow_posts ADD CONSTRAINT socialflow_posts_recurrence_id_fkey FOREIGN KEY (recurrence_id) REFERENCES socialflow_recurrences (id) ON DELETE SET NULL`,
  `ALTER TABLE socialflow_posts ADD CONSTRAINT socialflow_posts_workspace_id_socialflow_workspaces_id_fk FOREIGN KEY (workspace_id) REFERENCES socialflow_workspaces (id) ON DELETE CASCADE`,
  `ALTER TABLE socialflow_queue_slots ADD CONSTRAINT socialflow_queue_slots_connected_account_id_fkey FOREIGN KEY (connected_account_id) REFERENCES socialflow_connected_accounts (id) ON DELETE CASCADE`,
  `ALTER TABLE socialflow_recurrences ADD CONSTRAINT socialflow_recurrences_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES socialflow_users (id) ON DELETE SET NULL`,
  `ALTER TABLE socialflow_recurrences ADD CONSTRAINT socialflow_recurrences_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES socialflow_workspaces (id) ON DELETE CASCADE`,
  `ALTER TABLE socialflow_report_runs ADD CONSTRAINT socialflow_report_runs_schedule_id_fkey FOREIGN KEY (schedule_id) REFERENCES socialflow_report_schedules (id) ON DELETE CASCADE`,
  `ALTER TABLE socialflow_report_schedules ADD CONSTRAINT socialflow_report_schedules_account_id_fkey FOREIGN KEY (account_id) REFERENCES socialflow_connected_accounts (id) ON DELETE CASCADE`,
  `ALTER TABLE socialflow_report_schedules ADD CONSTRAINT socialflow_report_schedules_created_by_fkey FOREIGN KEY (created_by) REFERENCES socialflow_users (id) ON DELETE SET NULL`,
  `ALTER TABLE socialflow_report_schedules ADD CONSTRAINT socialflow_report_schedules_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES socialflow_workspaces (id) ON DELETE CASCADE`,
  `ALTER TABLE socialflow_sessions ADD CONSTRAINT socialflow_sessions_active_workspace_id_fkey FOREIGN KEY (active_workspace_id) REFERENCES socialflow_workspaces (id) ON DELETE SET NULL`,
  `ALTER TABLE socialflow_sessions ADD CONSTRAINT socialflow_sessions_user_id_socialflow_users_id_fk FOREIGN KEY (user_id) REFERENCES socialflow_users (id) ON DELETE CASCADE`,
  `ALTER TABLE socialflow_tags ADD CONSTRAINT socialflow_tags_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES socialflow_workspaces (id) ON DELETE CASCADE`,
  `ALTER TABLE socialflow_wordpress_connections ADD CONSTRAINT socialflow_wordpress_connections_automation_id_fkey FOREIGN KEY (automation_id) REFERENCES socialflow_automations (id) ON DELETE CASCADE`,
  `ALTER TABLE socialflow_wordpress_connections ADD CONSTRAINT socialflow_wordpress_connections_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES socialflow_workspaces (id) ON DELETE CASCADE`,
  `ALTER TABLE socialflow_workspace_members ADD CONSTRAINT socialflow_workspace_members_user_id_socialflow_users_id_fk FOREIGN KEY (user_id) REFERENCES socialflow_users (id) ON DELETE CASCADE`,
  `ALTER TABLE socialflow_workspace_members ADD CONSTRAINT socialflow_workspace_members_workspace_id_socialflow_workspaces FOREIGN KEY (workspace_id) REFERENCES socialflow_workspaces (id) ON DELETE CASCADE`,
  `ALTER TABLE socialflow_workspaces ADD CONSTRAINT socialflow_workspaces_owner_user_id_socialflow_users_id_fk FOREIGN KEY (owner_user_id) REFERENCES socialflow_users (id) ON DELETE SET NULL`,
];
